/*
 Lazy Load 1.9.3 - MIT license - Copyright 2010-2013 Mika Tuupola */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var h=g.value}catch(e){return this.context_.yieldAllIterator_=null,this.context_.throw_(e),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,g={next:function(){if(c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(a,b,c,g){if(b){c=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];h in c||(c[h]={});c=c[h]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var g=a.length,h=0;h<g;h++){var e=a[h];if(b.call(c,e,h,a))return{i:h,v:e}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var g=arguments[c];if(g)for(var h in g)$jscomp.owns(g,h)&&(a[h]=g[h])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,g){c=null!=c?c:function(a){return a};var b=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof e){a=e.call(a);for(var f=0;!(e=a.next()).done;)b.push(c.call(g,e.value,f++))}else for(e=a.length,f=0;f<e;f++)b.push(c.call(g,a[f],f));return b}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var h=b.length,e=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var f=0;f<e&&c<h;)if(b[c++]!=a[f++])return!1;return f>=e}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,g,h){return c==a&&"q"==g&&h==b}}));return!0===b.q}catch(c){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),c=Object.seal({}),b=new a([[d,2],[c,3]]);if(2!=b.get(d)||3!=b.get(c))return!1;b.delete(d);b.set(c,4);return!b.has(d)&&4==b.get(c)}catch(t){return!1}}function c(){}function g(a){var d=typeof a;return"object"===d&&null!==a||"function"===d}function h(a){if(!$jscomp.owns(a,f)){var d=new c;$jscomp.defineProperty(a,f,{value:d})}}function e(a){var d=Object[a];d&&(Object[a]=function(a){if(a instanceof
c)return a;h(a);return d(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var d=0,k=function(a){this.id_=(d+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};k.prototype.set=function(a,d){if(!g(a))throw Error("Invalid WeakMap key");h(a);if(!$jscomp.owns(a,f))throw Error("WeakMap key fail: "+
a);a[f][this.id_]=d;return this};k.prototype.get=function(a){return g(a)&&$jscomp.owns(a,f)?a[f][this.id_]:void 0};k.prototype.has=function(a){return g(a)&&$jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)};k.prototype.delete=function(a){return g(a)&&$jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)?delete a[f][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),c=new a($jscomp.makeIterator([[d,"s"]]));if("s"!=c.get(d)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var b=c.entries(),e=b.next();if(e.done||e.value[0]!=d||"s"!=e.value[1])return!1;e=b.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!b.next().done?!1:!0}catch(t){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=new WeakMap,g=function(a){this.data_={};this.head_=f();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};g.prototype.set=function(a,d){a=0===a?0:a;var c=h(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=d:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:d},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};g.prototype.delete=function(a){a=h(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};g.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};g.prototype.has=function(a){return!!h(this,a).entry};
g.prototype.get=function(a){return(a=h(this,a).entry)&&a.value};g.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};g.prototype.keys=function(){return e(this,function(a){return a.key})};g.prototype.values=function(){return e(this,function(a){return a.value})};g.prototype.forEach=function(a,d){for(var c=this.entries(),b;!(b=c.next()).done;)b=b.value,a.call(d,b[1],b[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var h=function(a,b){var e;var f=(e=b)&&typeof e;
"object"==f||"function"==f?c.has(e)?e=c.get(e):(f=""+ ++d,c.set(e,f),e=f):e="p_"+e;if((f=a.data_[e])&&$jscomp.owns(a.data_,e))for(a=0;a<f.length;a++){var g=f[a];if(b!==b&&g.key!==g.key||b===g.key)return{id:e,list:f,index:a,entry:g}}return{id:e,list:f,index:-1,entry:void 0}},e=function(a,d){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:d(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a=
{};return a.previous=a.next=a.head=a},d=0;return g},"es6","es3");
!function(a,b,c,g){var h=a(b);a.fn.lazyload=function(e){function f(){var d=0;k.each(function(){var c=a(this);if(!(l.skip_invisible&&!c.is(":visible")||a.abovethetop(this,l)||a.leftofbegin(this,l)))if(a.belowthefold(this,l)||a.rightoffold(this,l)){if(++d>l.failure_limit)return!1}else c.trigger("appear"),d=0})}var d,k=this,l={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:b,data_attribute:"original",skip_invisible:!0,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
return e&&(g!==e.failurelimit&&(e.failure_limit=e.failurelimit,delete e.failurelimit),g!==e.effectspeed&&(e.effect_speed=e.effectspeed,delete e.effectspeed),a.extend(l,e)),d=l.container===g||l.container===b?h:a(l.container),0===l.event.indexOf("scroll")&&d.bind(l.event,function(){return f()}),this.each(function(){var d=this,c=a(d);d.loaded=!1;(c.attr("src")===g||!1===c.attr("src"))&&c.is("img")&&c.attr("src",l.placeholder);c.one("appear",function(){this.loaded||(l.appear&&l.appear.call(d,k.length,
l),a("<img />").bind("load",function(){var b=c.attr("data-"+l.data_attribute);c.hide();c.is("img")?c.attr("src",b):c.css("background-image","url('"+b+"')");c[l.effect](l.effect_speed);d.loaded=!0;b=a.grep(k,function(a){return!a.loaded});(k=a(b),l.load)&&l.load.call(d,k.length,l)}).attr("src",c.attr("data-"+l.data_attribute)))});0!==l.event.indexOf("scroll")&&c.bind(l.event,function(){d.loaded||c.trigger("appear")})}),h.bind("resize",function(){f()}),/(?:iphone|ipod|ipad).*os 5/gi.test(navigator.appVersion)&&
h.bind("pageshow",function(d){d.originalEvent&&d.originalEvent.persisted&&k.each(function(){a(this).trigger("appear")})}),a(c).ready(function(){f()}),this};a.belowthefold=function(c,f){var d;return d=f.container===g||f.container===b?(b.innerHeight?b.innerHeight:h.height())+h.scrollTop():a(f.container).offset().top+a(f.container).height(),d<=a(c).offset().top-f.threshold};a.rightoffold=function(c,f){var d;return d=f.container===g||f.container===b?h.width()+h.scrollLeft():a(f.container).offset().left+
a(f.container).width(),d<=a(c).offset().left-f.threshold};a.abovethetop=function(c,f){var d;return d=f.container===g||f.container===b?h.scrollTop():a(f.container).offset().top,d>=a(c).offset().top+f.threshold+a(c).height()};a.leftofbegin=function(c,f){var d;return d=f.container===g||f.container===b?h.scrollLeft():a(f.container).offset().left,d>=a(c).offset().left+f.threshold+a(c).width()};a.inviewport=function(c,b){return!(a.rightoffold(c,b)||a.leftofbegin(c,b)||a.belowthefold(c,b)||a.abovethetop(c,
b))};a.extend(a.expr[":"],{"below-the-fold":function(c){return a.belowthefold(c,{threshold:0})},"above-the-top":function(c){return!a.belowthefold(c,{threshold:0})},"right-of-screen":function(c){return a.rightoffold(c,{threshold:0})},"left-of-screen":function(c){return!a.rightoffold(c,{threshold:0})},"in-viewport":function(c){return a.inviewport(c,{threshold:0})},"above-the-fold":function(c){return!a.belowthefold(c,{threshold:0})},"right-of-fold":function(c){return a.rightoffold(c,{threshold:0})},
"left-of-fold":function(c){return!a.rightoffold(c,{threshold:0})}})}(jQuery,window,document);
/*
 fancyBox v2.1.5 fancyapps.com | fancyapps.com/fancybox/#license */
(function(a,b,c,g){var h=c("html"),e=c(a),f=c(b),d=c.fancybox=function(){d.open.apply(this,arguments)},k=navigator.userAgent.match(/msie/i),l=null,n=b.createTouch!==g,p=function(a){return a&&a.hasOwnProperty&&a instanceof c},t=function(a){return a&&"string"===c.type(a)},B=function(a){return t(a)&&0<a.indexOf("%")},r=function(a,c){var m=parseInt(a,10)||0;c&&B(a)&&(m*=d.getViewport()[c]/100);return Math.ceil(m)},w=function(a,d){return r(a,d)+"px"};c.extend(d,{version:"2.1.5",defaults:{padding:15,margin:20,
width:800,height:600,minWidth:100,minHeight:100,maxWidth:9999,maxHeight:9999,pixelRatio:1,autoSize:!0,autoHeight:!1,autoWidth:!1,autoResize:!0,autoCenter:!n,fitToView:!0,aspectRatio:!1,topRatio:.5,leftRatio:.5,scrolling:"auto",wrapCSS:"",arrows:!0,closeBtn:!0,closeClick:!1,nextClick:!1,mouseWheel:!0,autoPlay:!1,playSpeed:3E3,preload:3,modal:!1,loop:!0,ajax:{dataType:"html",headers:{"X-fancyBox":!0}},iframe:{scrolling:"auto",preload:!0},swf:{wmode:"transparent",allowfullscreen:"true",allowscriptaccess:"always"},
keys:{next:{13:"left",34:"up",39:"left",40:"up"},prev:{8:"right",33:"down",37:"right",38:"down"},close:[27],play:[32],toggle:[70]},direction:{next:"left",prev:"right"},scrollOutside:!0,index:0,type:null,href:null,content:null,title:null,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1"><div class="fancybox-skin"><div class="fancybox-outer"><div class="fancybox-inner"></div></div></div></div>',image:'<img class="fancybox-image" src="{href}" alt="" />',iframe:'<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen'+
(k?' allowtransparency="true"':"")+"></iframe>",error:'<p class="fancybox-error">The requested content cannot be loaded.<br/>Please try again later.</p>',closeBtn:'<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>',next:'<a title="Next" class="fancybox-nav fancybox-next" href="javascript:;"><span></span></a>',prev:'<a title="Previous" class="fancybox-nav fancybox-prev" href="javascript:;"><span></span></a>'},openEffect:"fade",openSpeed:250,openEasing:"swing",openOpacity:!0,
openMethod:"zoomIn",closeEffect:"fade",closeSpeed:250,closeEasing:"swing",closeOpacity:!0,closeMethod:"zoomOut",nextEffect:"elastic",nextSpeed:250,nextEasing:"swing",nextMethod:"changeIn",prevEffect:"elastic",prevSpeed:250,prevEasing:"swing",prevMethod:"changeOut",helpers:{overlay:!0,title:!0},onCancel:c.noop,beforeLoad:c.noop,afterLoad:c.noop,beforeShow:c.noop,afterShow:c.noop,beforeChange:c.noop,beforeClose:c.noop,afterClose:c.noop},group:{},opts:{},previous:null,coming:null,current:null,isActive:!1,
isOpen:!1,isOpened:!1,wrap:null,skin:null,outer:null,inner:null,player:{timer:null,isActive:!1},ajaxLoad:null,imgPreload:null,transitions:{},helpers:{},open:function(a,b){if(a&&(c.isPlainObject(b)||(b={}),!1!==d.close(!0)))return c.isArray(a)||(a=p(a)?c(a).get():[a]),c.each(a,function(m,e){var q={},u,G;"object"===c.type(e)&&(e.nodeType&&(e=c(e)),p(e)?(q={href:e.data("fancybox-href")||e.attr("href"),title:e.data("fancybox-title")||e.attr("title"),isDom:!0,element:e},c.metadata&&c.extend(!0,q,e.metadata())):
q=e);var f=b.href||q.href||(t(e)?e:null);var h=b.title!==g?b.title:q.title||"";var k=(u=b.content||q.content)?"html":b.type||q.type;!k&&q.isDom&&(k=e.data("fancybox-type"),k||(k=(k=e.prop("class").match(/fancybox\.(\w+)/))?k[1]:null));t(f)&&(k||(d.isImage(f)?k="image":d.isSWF(f)?k="swf":"#"===f.charAt(0)?k="inline":t(e)&&(k="html",u=e)),"ajax"===k&&(G=f.split(/\s+/,2),f=G.shift(),G=G.shift()));u||("inline"===k?f?u=c(t(f)?f.replace(/.*(?=#[^\s]+$)/,""):f):q.isDom&&(u=e):"html"===k?u=f:!k&&!f&&q.isDom&&
(k="inline",u=e));c.extend(q,{href:f,type:k,content:u,title:h,selector:G});a[m]=q}),d.opts=c.extend(!0,{},d.defaults,b),b.keys!==g&&(d.opts.keys=b.keys?c.extend({},d.defaults.keys,b.keys):!1),d.group=a,d._start(d.opts.index)},cancel:function(){var a=d.coming;a&&!1!==d.trigger("onCancel")&&(d.hideLoading(),d.ajaxLoad&&d.ajaxLoad.abort(),d.ajaxLoad=null,d.imgPreload&&(d.imgPreload.onload=d.imgPreload.onerror=null),a.wrap&&a.wrap.stop(!0,!0).trigger("onReset").remove(),d.coming=null,d.current||d._afterZoomOut(a))},
close:function(a){d.cancel();!1!==d.trigger("beforeClose")&&(d.unbindEvents(),d.isActive&&(d.isOpen&&!0!==a?(d.isOpen=d.isOpened=!1,d.isClosing=!0,c(".fancybox-item, .fancybox-nav").remove(),d.wrap.stop(!0,!0).removeClass("fancybox-opened"),d.transitions[d.current.closeMethod]()):(c(".fancybox-wrap").stop(!0).trigger("onReset").remove(),d._afterZoomOut())))},play:function(a){var c=function(){clearTimeout(d.player.timer)},b=function(){c();d.current&&d.player.isActive&&(d.player.timer=setTimeout(d.next,
d.current.playSpeed))},m=function(){c();f.unbind(".player");d.player.isActive=!1;d.trigger("onPlayEnd")};!0===a||!d.player.isActive&&!1!==a?d.current&&(d.current.loop||d.current.index<d.group.length-1)&&(d.player.isActive=!0,f.bind({"onCancel.player beforeClose.player":m,"onUpdate.player":b,"beforeLoad.player":c}),b(),d.trigger("onPlayStart")):m()},next:function(a){var c=d.current;c&&(t(a)||(a=c.direction.next),d.jumpto(c.index+1,a,"next"))},prev:function(a){var c=d.current;c&&(t(a)||(a=c.direction.prev),
d.jumpto(c.index-1,a,"prev"))},jumpto:function(a,c,b){var m=d.current;m&&(a=r(a),d.direction=c||m.direction[a>=m.index?"next":"prev"],d.router=b||"jumpto",m.loop&&(0>a&&(a=m.group.length+a%m.group.length),a%=m.group.length),m.group[a]!==g&&(d.cancel(),d._start(a)))},reposition:function(a,b){var m=d.current,e=m?m.wrap:null,q;e&&(q=d._getPosition(b),a&&"scroll"===a.type?(delete q.position,e.stop(!0,!0).animate(q,200)):(e.css(q),m.pos=c.extend({},m.dim,q)))},update:function(a){var c=a&&a.type,b=!c||
"orientationchange"===c;b&&(clearTimeout(l),l=null);d.isOpen&&!l&&(l=setTimeout(function(){var m=d.current;m&&!d.isClosing&&(d.wrap.removeClass("fancybox-tmp"),(b||"load"===c||"resize"===c&&m.autoResize)&&d._setDimension(),"scroll"===c&&m.canShrink||d.reposition(a),d.trigger("onUpdate"),l=null)},b&&!n?0:300))},toggle:function(a){d.isOpen&&(d.current.fitToView="boolean"===c.type(a)?a:!d.current.fitToView,n&&(d.wrap.removeAttr("style").addClass("fancybox-tmp"),d.trigger("onUpdate")),d.update())},hideLoading:function(){f.unbind(".loading");
c("#fancybox-loading").remove()},showLoading:function(){var a;d.hideLoading();var b=c('<div id="fancybox-loading"><div></div></div>').click(d.cancel).appendTo("body");f.bind("keydown.loading",function(a){27===(a.which||a.keyCode)&&(a.preventDefault(),d.cancel())});d.defaults.fixed||(a=d.getViewport(),b.css({position:"absolute",top:.5*a.h+a.y,left:.5*a.w+a.x}))},getViewport:function(){var c=d.current&&d.current.locked||!1,b={x:e.scrollLeft(),y:e.scrollTop()};c?(b.w=c[0].clientWidth,b.h=c[0].clientHeight):
(b.w=n&&a.innerWidth?a.innerWidth:e.width(),b.h=n&&a.innerHeight?a.innerHeight:e.height());return b},unbindEvents:function(){d.wrap&&p(d.wrap)&&d.wrap.unbind(".fb");f.unbind(".fb");e.unbind(".fb")},bindEvents:function(){var a=d.current,b;a&&(e.bind("orientationchange.fb"+(n?"":" resize.fb")+(a.autoCenter&&!a.locked?" scroll.fb":""),d.update),(b=a.keys)&&f.bind("keydown.fb",function(m){var e=m.which||m.keyCode,q=m.target||m.srcElement;if(27===e&&d.coming)return!1;m.ctrlKey||m.altKey||m.shiftKey||m.metaKey||
q&&(q.type||c(q).is("[contenteditable]"))||c.each(b,function(b,q){if(1<a.group.length&&q[e]!==g)return d[b](q[e]),m.preventDefault(),!1;if(-1<c.inArray(e,q))return d[b](),m.preventDefault(),!1})}),c.fn.mousewheel&&a.mouseWheel&&d.wrap.bind("mousewheel.fb",function(b,m,e,q){for(var f=c(b.target||null),u=!1;f.length&&!u&&!f.is(".fancybox-skin")&&!f.is(".fancybox-wrap");)u=f[0]&&!(f[0].style.overflow&&"hidden"===f[0].style.overflow)&&(f[0].clientWidth&&f[0].scrollWidth>f[0].clientWidth||f[0].clientHeight&&
f[0].scrollHeight>f[0].clientHeight),f=c(f).parent();0!==m&&!u&&1<d.group.length&&!a.canShrink&&(0<q||0<e?d.prev(0<q?"down":"left"):(0>q||0>e)&&d.next(0>q?"up":"right"),b.preventDefault())}))},trigger:function(a,b){var m,e=b||d.coming||d.current;if(e){c.isFunction(e[a])&&(m=e[a].apply(e,Array.prototype.slice.call(arguments,1)));if(!1===m)return!1;e.helpers&&c.each(e.helpers,function(b,m){if(m&&d.helpers[b]&&c.isFunction(d.helpers[b][a]))d.helpers[b][a](c.extend(!0,{},d.helpers[b].defaults,m),e)});
f.trigger(a)}},isImage:function(a){return t(a)&&a.match(/(^data:image\/.*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg)((\?|#).*)?$)/i)},isSWF:function(a){return t(a)&&a.match(/\.(swf)((\?|#).*)?$/i)},_start:function(a){var b={};a=r(a);var e=d.group[a]||null;if(!e)return!1;b=c.extend(!0,{},d.opts,e);e=b.margin;var m=b.padding;"number"===c.type(e)&&(b.margin=[e,e,e,e]);"number"===c.type(m)&&(b.padding=[m,m,m,m]);b.modal&&c.extend(!0,b,{closeBtn:!1,closeClick:!1,nextClick:!1,arrows:!1,mouseWheel:!1,keys:null,
helpers:{overlay:{closeClick:!1}}});b.autoSize&&(b.autoWidth=b.autoHeight=!0);"auto"===b.width&&(b.autoWidth=!0);"auto"===b.height&&(b.autoHeight=!0);b.group=d.group;b.index=a;d.coming=b;if(!1===d.trigger("beforeLoad"))d.coming=null;else{m=b.type;e=b.href;if(!m)return d.coming=null,d.current&&d.router&&"jumpto"!==d.router?(d.current.index=a,d[d.router](d.direction)):!1;d.isActive=!0;if("image"===m||"swf"===m)b.autoHeight=b.autoWidth=!1,b.scrolling="visible";"image"===m&&(b.aspectRatio=!0);"iframe"===
m&&n&&(b.scrolling="scroll");b.wrap=c(b.tpl.wrap).addClass("fancybox-"+(n?"mobile":"desktop")+" fancybox-type-"+m+" fancybox-tmp "+b.wrapCSS).appendTo(b.parent||"body");c.extend(b,{skin:c(".fancybox-skin",b.wrap),outer:c(".fancybox-outer",b.wrap),inner:c(".fancybox-inner",b.wrap)});c.each(["Top","Right","Bottom","Left"],function(a,c){b.skin.css("padding"+c,w(b.padding[a]))});d.trigger("onReady");if("inline"===m||"html"===m){if(!b.content||!b.content.length)return d._error("content")}else if(!e)return d._error("href");
"image"===m?d._loadImage():"ajax"===m?d._loadAjax():"iframe"===m?d._loadIframe():d._afterLoad()}},_error:function(a){c.extend(d.coming,{type:"html",autoWidth:!0,autoHeight:!0,minWidth:0,minHeight:0,scrolling:"no",hasError:a,content:d.coming.tpl.error});d._afterLoad()},_loadImage:function(){var a=d.imgPreload=new Image;a.onload=function(){this.onload=this.onerror=null;d.coming.width=this.width/d.opts.pixelRatio;d.coming.height=this.height/d.opts.pixelRatio;d._afterLoad()};a.onerror=function(){this.onload=
this.onerror=null;d._error("image")};a.src=d.coming.href;!0!==a.complete&&d.showLoading()},_loadAjax:function(){var a=d.coming;d.showLoading();d.ajaxLoad=c.ajax(c.extend({},a.ajax,{url:a.href,error:function(a,c){d.coming&&"abort"!==c?d._error("ajax",a):d.hideLoading()},success:function(c,b){"success"===b&&(a.content=c,d._afterLoad())}}))},_loadIframe:function(){var a=d.coming,b=c(a.tpl.iframe.replace(/\{rnd\}/g,(new Date).getTime())).attr("scrolling",n?"auto":a.iframe.scrolling).attr("src",a.href);
c(a.wrap).bind("onReset",function(){try{c(this).find("iframe").hide().attr("src","//about:blank").end().empty()}catch(u){}});a.iframe.preload&&(d.showLoading(),b.one("load",function(){c(this).data("ready",1);n||c(this).bind("load.fb",d.update);c(this).parents(".fancybox-wrap").width("100%").removeClass("fancybox-tmp").show();d._afterLoad()}));a.content=b.appendTo(a.inner);a.iframe.preload||d._afterLoad()},_preloadImages:function(){var a=d.group,c=d.current,b=a.length,e=c.preload?Math.min(c.preload,
b-1):0,f;for(f=1;f<=e;f+=1){var g=a[(c.index+f)%b];"image"===g.type&&g.href&&((new Image).src=g.href)}},_afterLoad:function(){var a=d.coming,b=d.current;d.hideLoading();if(a&&!1!==d.isActive)if(!1===d.trigger("afterLoad",a,b))a.wrap.stop(!0).trigger("onReset").remove(),d.coming=null;else{b&&(d.trigger("beforeChange",b),b.wrap.stop(!0).removeClass("fancybox-opened").find(".fancybox-item, .fancybox-nav").remove());d.unbindEvents();var e=a.content;var f=a.type;var g=a.scrolling;c.extend(d,{wrap:a.wrap,
skin:a.skin,outer:a.outer,inner:a.inner,current:a,previous:b});var k=a.href;switch(f){case "inline":case "ajax":case "html":a.selector?e=c("<div>").html(e).find(a.selector):p(e)&&(e.data("fancybox-placeholder")||e.data("fancybox-placeholder",c('<div class="fancybox-placeholder"></div>').insertAfter(e).hide()),e=e.show().detach(),a.wrap.bind("onReset",function(){c(this).find(e).length&&e.hide().replaceAll(e.data("fancybox-placeholder")).data("fancybox-placeholder",!1)}));break;case "image":e=a.tpl.image.replace("{href}",
k);break;case "swf":e='<object id="fancybox-swf" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%"><param name="movie" value="'+k+'"></param>';var h="";c.each(a.swf,function(a,c){e+='<param name="'+a+'" value="'+c+'"></param>';h+=" "+a+'="'+c+'"'});e+='<embed src="'+k+'" type="application/x-shockwave-flash" width="100%" height="100%"'+h+"></embed></object>"}p(e)&&e.parent().is(a.inner)||a.inner.append(e);d.trigger("beforeShow");a.inner.css("overflow","yes"===g?"scroll":
"no"===g?"hidden":g);d._setDimension();d.reposition();d.isOpen=!1;d.coming=null;d.bindEvents();if(d.isOpened){if(b.prevMethod)d.transitions[b.prevMethod]()}else c(".fancybox-wrap").not(a.wrap).stop(!0).trigger("onReset").remove();d.transitions[d.isOpened?a.nextMethod:a.openMethod]();d._preloadImages()}},_setDimension:function(){var a=d.getViewport(),b=0;var e=d.wrap;var f=d.skin,g=d.inner,k=d.current;var h=k.width;var l=k.height,p=k.minWidth,n=k.minHeight,t=k.maxWidth,v=k.maxHeight,M=k.scrolling,
I=k.scrollOutside?k.scrollbarWidth:0,x=k.margin,y=r(x[1]+x[3]),E=r(x[0]+x[2]),F,H;e.add(f).add(g).width("auto").height("auto").removeClass("fancybox-tmp");x=r(f.outerWidth(!0)-f.width());var K=r(f.outerHeight(!0)-f.height());var z=y+x;var J=E+K;var C=B(h)?(a.w-z)*r(h)/100:h;var A=B(l)?(a.h-J)*r(l)/100:l;if("iframe"===k.type){if(H=k.content,k.autoHeight&&1===H.data("ready"))try{H[0].contentWindow.document.location&&(g.width(C).height(9999),F=H.contents().find("body"),I&&F.css("overflow-x","hidden"),
A=F.outerHeight(!0))}catch(N){}}else if(k.autoWidth||k.autoHeight)g.addClass("fancybox-tmp"),k.autoWidth||g.width(C),k.autoHeight||g.height(A),k.autoWidth&&(C=g.width()),k.autoHeight&&(A=g.height()),g.removeClass("fancybox-tmp");h=r(C);l=r(A);var D=C/A;p=r(B(p)?r(p,"w")-z:p);t=r(B(t)?r(t,"w")-z:t);n=r(B(n)?r(n,"h")-J:n);v=r(B(v)?r(v,"h")-J:v);F=t;var L=v;k.fitToView&&(t=Math.min(a.w-z,t),v=Math.min(a.h-J,v));z=a.w-y;E=a.h-E;k.aspectRatio?(h>t&&(h=t,l=r(h/D)),l>v&&(l=v,h=r(l*D)),h<p&&(h=p,l=r(h/D)),
l<n&&(l=n,h=r(l*D))):(h=Math.max(p,Math.min(h,t)),k.autoHeight&&"iframe"!==k.type&&(g.width(h),l=g.height()),l=Math.max(n,Math.min(l,v)));if(k.fitToView)if(g.width(h).height(l),e.width(h+x),a=e.width(),y=e.height(),k.aspectRatio)for(;(a>z||y>E)&&h>p&&l>n&&!(19<b++);)l=Math.max(n,Math.min(v,l-10)),h=r(l*D),h<p&&(h=p,l=r(h/D)),h>t&&(h=t,l=r(h/D)),g.width(h).height(l),e.width(h+x),a=e.width(),y=e.height();else h=Math.max(p,Math.min(h,h-(a-z))),l=Math.max(n,Math.min(l,l-(y-E)));I&&"auto"===M&&l<A&&h+
x+I<z&&(h+=I);g.width(h).height(l);e.width(h+x);a=e.width();y=e.height();e=(a>z||y>E)&&h>p&&l>n;h=k.aspectRatio?h<F&&l<L&&h<C&&l<A:(h<F||l<L)&&(h<C||l<A);c.extend(k,{dim:{width:w(a),height:w(y)},origWidth:C,origHeight:A,canShrink:e,canExpand:h,wPadding:x,hPadding:K,wrapSpace:y-f.outerHeight(!0),skinSpace:f.height()-l});!H&&k.autoHeight&&l>n&&l<v&&!h&&g.height("auto")},_getPosition:function(a){var c=d.current,b=d.getViewport(),e=c.margin,f=d.wrap.width()+e[1]+e[3],m=d.wrap.height()+e[0]+e[2];e={position:"absolute",
top:e[0],left:e[3]};c.autoCenter&&c.fixed&&!a&&m<=b.h&&f<=b.w?e.position="fixed":c.locked||(e.top+=b.y,e.left+=b.x);e.top=w(Math.max(e.top,e.top+(b.h-m)*c.topRatio));e.left=w(Math.max(e.left,e.left+(b.w-f)*c.leftRatio));return e},_afterZoomIn:function(){var a=d.current;a&&(d.isOpen=d.isOpened=!0,d.wrap.css("overflow","visible").addClass("fancybox-opened"),d.update(),(a.closeClick||a.nextClick&&1<d.group.length)&&d.inner.css("cursor","pointer").bind("click.fb",function(b){c(b.target).is("a")||c(b.target).parent().is("a")||
(b.preventDefault(),d[a.closeClick?"close":"next"]())}),a.closeBtn&&c(a.tpl.closeBtn).appendTo(d.skin).bind("click.fb",function(a){a.preventDefault();d.close()}),a.arrows&&1<d.group.length&&((a.loop||0<a.index)&&c(a.tpl.prev).appendTo(d.outer).bind("click.fb",d.prev),(a.loop||a.index<d.group.length-1)&&c(a.tpl.next).appendTo(d.outer).bind("click.fb",d.next)),d.trigger("afterShow"),a.loop||a.index!==a.group.length-1?d.opts.autoPlay&&!d.player.isActive&&(d.opts.autoPlay=!1,d.play()):d.play(!1))},_afterZoomOut:function(a){a=
a||d.current;c(".fancybox-wrap").trigger("onReset").remove();c.extend(d,{group:{},opts:{},router:!1,current:null,isActive:!1,isOpened:!1,isOpen:!1,isClosing:!1,wrap:null,skin:null,outer:null,inner:null});d.trigger("afterClose",a)}});d.transitions={getOrigPosition:function(){var a=d.current,c=a.element,b=a.orig,e={},f=50,g=50,h=a.hPadding,k=a.wPadding,l=d.getViewport();!b&&a.isDom&&c.is(":visible")&&(b=c.find("img:first"),b.length||(b=c));p(b)?(e=b.offset(),b.is("img")&&(f=b.outerWidth(),g=b.outerHeight())):
(e.top=l.y+(l.h-g)*a.topRatio,e.left=l.x+(l.w-f)*a.leftRatio);if("fixed"===d.wrap.css("position")||a.locked)e.top-=l.y,e.left-=l.x;return{top:w(e.top-h*a.topRatio),left:w(e.left-k*a.leftRatio),width:w(f+k),height:w(g+h)}},step:function(a,c){var b=c.prop;var e=d.current;var f=e.wrapSpace,g=e.skinSpace;if("width"===b||"height"===b)c=c.end===c.start?1:(a-c.start)/(c.end-c.start),d.isClosing&&(c=1-c),e="width"===b?e.wPadding:e.hPadding,e=a-e,d.skin[b](r("width"===b?e:e-f*c)),d.inner[b](r("width"===b?
e:e-f*c-g*c))},zoomIn:function(){var a=d.current,b=a.pos,e=a.openEffect,f="elastic"===e,g=c.extend({opacity:1},b);delete g.position;f?(b=this.getOrigPosition(),a.openOpacity&&(b.opacity=.1)):"fade"===e&&(b.opacity=.1);d.wrap.css(b).animate(g,{duration:"none"===e?0:a.openSpeed,easing:a.openEasing,step:f?this.step:null,complete:d._afterZoomIn})},zoomOut:function(){var a=d.current,c=a.closeEffect,b="elastic"===c,e={opacity:.1};b&&(e=this.getOrigPosition(),a.closeOpacity&&(e.opacity=.1));d.wrap.animate(e,
{duration:"none"===c?0:a.closeSpeed,easing:a.closeEasing,step:b?this.step:null,complete:d._afterZoomOut})},changeIn:function(){var a=d.current,c=a.nextEffect,b=a.pos,e={opacity:1},f=d.direction,g;b.opacity=.1;"elastic"===c&&(g="down"===f||"up"===f?"top":"left","down"===f||"right"===f?(b[g]=w(r(b[g])-200),e[g]="+=200px"):(b[g]=w(r(b[g])+200),e[g]="-=200px"));"none"===c?d._afterZoomIn():d.wrap.css(b).animate(e,{duration:a.nextSpeed,easing:a.nextEasing,complete:d._afterZoomIn})},changeOut:function(){var a=
d.previous,b=a.prevEffect,e={opacity:.1},f=d.direction;"elastic"===b&&(e["down"===f||"up"===f?"top":"left"]=("up"===f||"left"===f?"-":"+")+"=200px");a.wrap.animate(e,{duration:"none"===b?0:a.prevSpeed,easing:a.prevEasing,complete:function(){c(this).trigger("onReset").remove()}})}};d.helpers.overlay={defaults:{closeClick:!0,speedOut:200,showEarly:!0,css:{},locked:!n,fixed:!0},overlay:null,fixed:!1,el:c("html"),create:function(a){a=c.extend({},this.defaults,a);this.overlay&&this.close();this.overlay=
c('<div class="fancybox-overlay"></div>').appendTo(d.coming?d.coming.parent:a.parent);this.fixed=!1;a.fixed&&d.defaults.fixed&&(this.overlay.addClass("fancybox-overlay-fixed"),this.fixed=!0)},open:function(a){var b=this;a=c.extend({},this.defaults,a);this.overlay?this.overlay.unbind(".overlay").width("auto").height("auto"):this.create(a);this.fixed||(e.bind("resize.overlay",c.proxy(this.update,this)),this.update());a.closeClick&&this.overlay.bind("click.overlay",function(a){if(c(a.target).hasClass("fancybox-overlay"))return d.isActive?
d.close():b.close(),!1});this.overlay.css(a.css).show()},close:function(){var a,b;e.unbind("resize.overlay");this.el.hasClass("fancybox-lock")&&(c(".fancybox-margin").removeClass("fancybox-margin"),a=e.scrollTop(),b=e.scrollLeft(),this.el.removeClass("fancybox-lock"),e.scrollTop(a).scrollLeft(b));c(".fancybox-overlay").remove().hide();c.extend(this,{overlay:null,fixed:!1})},update:function(){var a="100%",c;this.overlay.width(a).height("100%");k?(c=Math.max(b.documentElement.offsetWidth,b.body.offsetWidth),
f.width()>c&&(a=f.width())):f.width()>e.width()&&(a=f.width());this.overlay.width(a).height(f.height())},onReady:function(a,b){var d=this.overlay;c(".fancybox-overlay").stop(!0,!0);d||this.create(a);a.locked&&this.fixed&&b.fixed&&(d||(this.margin=f.height()>e.height()?c("html").css("margin-right").replace("px",""):!1),b.locked=this.overlay.append(b.wrap),b.fixed=!1);!0===a.showEarly&&this.beforeShow.apply(this,arguments)},beforeShow:function(a,b){var d,f;b.locked&&(!1!==this.margin&&(c("*").filter(function(){return"fixed"===
c(this).css("position")&&!c(this).hasClass("fancybox-overlay")&&!c(this).hasClass("fancybox-wrap")}).addClass("fancybox-margin"),this.el.addClass("fancybox-margin")),d=e.scrollTop(),f=e.scrollLeft(),this.el.addClass("fancybox-lock"),e.scrollTop(d).scrollLeft(f));this.open(a)},onUpdate:function(){this.fixed||this.update()},afterClose:function(a){this.overlay&&!d.coming&&this.overlay.fadeOut(a.speedOut,c.proxy(this.close,this))}};d.helpers.title={defaults:{type:"float",position:"bottom"},beforeShow:function(a){var b=
d.current,e=b.title,f=a.type;c.isFunction(e)&&(e=e.call(b.element,b));if(t(e)&&""!==c.trim(e)){b=c('<div class="fancybox-title fancybox-title-'+f+'-wrap">'+e+"</div>");switch(f){case "inside":f=d.skin;break;case "outside":f=d.wrap;break;case "over":f=d.inner;break;default:f=d.skin,b.appendTo("body"),k&&b.width(b.width()),b.wrapInner('<span class="child"></span>'),d.current.margin[2]+=Math.abs(r(b.css("margin-bottom")))}b["top"===a.position?"prependTo":"appendTo"](f)}}};c.fn.fancybox=function(a){var b=
c(this),e=this.selector||"",g=function(f){var g=c(this).blur(),k=h,l,p;f.ctrlKey||f.altKey||f.shiftKey||f.metaKey||g.is(".fancybox-wrap")||(l=a.groupAttr||"data-fancybox-group",p=g.attr(l),p||(l="rel",p=g.get(0)[l]),p&&""!==p&&"nofollow"!==p&&(g=e.length?c(e):b,g=g.filter("["+l+'="'+p+'"]'),k=g.index(this)),a.index=k,!1===d.open(g,a)||f.preventDefault())};a=a||{};var h=a.index||0;e&&!1!==a.live?f.undelegate(e,"click.fb-start").delegate(e+":not('.fancybox-item, .fancybox-nav')","click.fb-start",g):
b.unbind("click.fb-start").bind("click.fb-start",g);this.filter("[data-fancybox-start=1]").trigger("click");return this};f.ready(function(){c.scrollbarWidth===g&&(c.scrollbarWidth=function(){var a=c('<div style="width:50px;height:50px;overflow:auto"><div/></div>').appendTo("body"),b=a.children();b=b.innerWidth()-b.height(99).innerWidth();a.remove();return b});if(c.support.fixedPosition===g){var b=c.support;var e=c('<div style="position:fixed;top:20px;"></div>').appendTo("body");var f=20===e[0].offsetTop||
15===e[0].offsetTop;e.remove();b.fixedPosition=f}c.extend(d.defaults,{scrollbarWidth:c.scrollbarWidth(),fixed:c.support.fixedPosition,parent:c("body")});b=c(a).width();h.addClass("fancybox-lock-test");e=c(a).width();h.removeClass("fancybox-lock-test");c("<style type='text/css'>.fancybox-margin{margin-right:"+(e-b)+"px;}</style>").appendTo("head")})})(window,document,jQuery);
/*
 http://mths.be/placeholder v2.0.7 by @mathias */
(function(a,b,c){function g(a){var b={},d=/^jQuery\d+$/;c.each(a.attributes,function(a,c){c.specified&&!d.test(c.name)&&(b[c.name]=c.value)});return b}function h(a,d){var e=c(this);if(this.value==e.attr("placeholder")&&e.hasClass("placeholder"))if(e.data("placeholder-password")){e=e.hide().next().show().attr("id",e.removeAttr("id").data("placeholder-id"));if(!0===a)return e[0].value=d;e.focus()}else this.value="",e.removeClass("placeholder"),this==b.activeElement&&this.select()}function e(){var a=
c(this),b=this.id;if(""==this.value){if("password"==this.type){if(!a.data("placeholder-textinput")){try{var d=a.clone().attr({type:"text"})}catch(B){d=c("<input>").attr(c.extend(g(this),{type:"text"}))}d.removeAttr("name").data({"placeholder-password":!0,"placeholder-id":b}).bind("focus.placeholder",h);a.data({"placeholder-textinput":d,"placeholder-id":b}).before(d)}a=a.removeAttr("id").hide().prev().attr("id",b).show()}a.addClass("placeholder");a[0].value=a.attr("placeholder")}else a.removeClass("placeholder")}
var f="placeholder"in b.createElement("input"),d="placeholder"in b.createElement("textarea"),k=c.fn,l=c.valHooks;f&&d?(k=k.placeholder=function(){return this},k.input=k.textarea=!0):(k=k.placeholder=function(){this.filter((f?"textarea":":input")+"[placeholder]").not(".placeholder").bind({"focus.placeholder":h,"blur.placeholder":e}).data("placeholder-enabled",!0).trigger("blur.placeholder");return this},k.input=f,k.textarea=d,k={get:function(a){var b=c(a);return b.data("placeholder-enabled")&&b.hasClass("placeholder")?
"":a.value},set:function(a,d){var f=c(a);if(!f.data("placeholder-enabled"))return a.value=d;""==d?(a.value=d,a!=b.activeElement&&e.call(a)):f.hasClass("placeholder")?h.call(a,!0,d)||(a.value=d):a.value=d;return f}},f||(l.input=k),d||(l.textarea=k),c(function(){c(b).delegate("form","submit.placeholder",function(){var a=c(".placeholder",this).each(h);setTimeout(function(){a.each(e)},10)})}),c(a).bind("beforeunload.placeholder",function(){c(".placeholder").each(function(){this.value=""})}))})(this,document,
jQuery);
(function(a){function b(a,b){return"function"==typeof a?a.call(b):a}function c(a){for(;a=a.parentNode;)if(a==document)return!0;return!1}function g(b,c){this.$element=a(b);this.options=c;this.enabled=!0;this.fixTitle();this.allowKeyboardNavigation()}var h=0;g.prototype={show:function(){if(c(this.$element[0])){var e=this.getTitle();if(e&&this.enabled){var f=function(){"in"!=l.hoverState&&(l.hoverTooltip=!1,"manual"!=l.options.trigger&&l.$element.trigger("hover"==l.options.trigger?"mouseleave.tipsy":
"blur.tipsy"))},d=function(){l.hoverTooltip=!0},g=this.tip();g.find(".tipsy-inner")[this.options.html?"html":"text"](e);g[0].className="tipsy";g.remove().css({top:0,left:0,visibility:"hidden",display:"block"}).appendTo(document.body);var l=this;this.options.hoverable&&g.hover(d,f);this.options.className&&g.addClass(b(this.options.className,this.$element[0]));e=a.extend({},this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight});f=g[0].offsetWidth;d=g[0].offsetHeight;
var n=b(this.options.gravity,this.$element[0]);switch(n.charAt(0)){case "n":var p={top:e.top+e.height+this.options.offset,left:e.left+e.width/2-f/2};break;case "s":p={top:e.top-d-this.options.offset,left:e.left+e.width/2-f/2};break;case "e":p={top:e.top+e.height/2-d/2,left:e.left-f-this.options.offset};break;case "w":p={top:e.top+e.height/2-d/2,left:e.left+e.width+this.options.offset}}2==n.length&&("w"==n.charAt(1)?p.left=e.left+e.width/2-15:p.left=e.left+e.width/2-f+15);g.css(p).addClass("tipsy-"+
n);g.find(".tipsy-arrow")[0].className="tipsy-arrow tipsy-arrow-"+n.charAt(0);this.options.fade?g.stop().css({opacity:0,display:"block",visibility:"visible"}).animate({opacity:this.options.opacity}):g.css({visibility:"visible",opacity:this.options.opacity});this.options.aria&&(p="tipsyuid"+h++,g.attr("id",p),this.$element.attr("aria-describedby",p))}}},hide:function(){this.options.fade?this.tip().stop().fadeOut(function(){a(this).remove()}):this.tip().remove();this.options.aria&&this.$element.removeAttr("aria-describedby")},
fixTitle:function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},allowKeyboardNavigation:function(){0===this.$element.find(":focusable").length&&this.$element.attr("tabindex",0)},getTitle:function(){var a,b=this.$element;this.fixTitle();var c=this.options;"string"==typeof c.title?a=b.attr("title"==c.title?"data-original-title":c.title):"function"==typeof c.title&&(a=c.title.call(b[0]));
return(a=(""+a).replace(/(^\s*|\s*$)/,""))||c.fallback},tip:function(){this.$tip||(this.$tip=a('<div class="tipsy"></div>').html('<div class="tipsy-arrow"></div><div class="tipsy-inner"></div>').attr("role","tooltip"),this.$tip.data("tipsy-pointee",this.$element[0]));return this.$tip},validate:function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled}};
a.fn.tipsy=function(b){function c(c){var d=a.data(c,"tipsy");d||(d=new g(c,a.fn.tipsy.elementOptions(c,b)),a.data(c,"tipsy",d));return d}function d(){var a=c(this);a.hoverState="in";0==b.delayIn?a.show():(a.fixTitle(),setTimeout(function(){"in"==a.hoverState&&a.show()},b.delayIn))}function e(){var a=c(this);a.hoverState="out";0==b.delayOut?a.hide():setTimeout(function(){"out"!=a.hoverState||a.hoverTooltip||a.hide()},b.delayOut)}if(!0===b)return this.data("tipsy");if("string"==typeof b){var h=this.data("tipsy");
if(h)h[b]();return this}b=a.extend({},a.fn.tipsy.defaults,b);b.hoverable&&(b.delayOut=b.delayOut||20);b.live||this.each(function(){c(this)});if("manual"!=b.trigger){h="hover"==b.trigger?"mouseenter.tipsy focus.tipsy":"focus.tipsy";var n="hover"==b.trigger?"mouseleave.tipsy blur.tipsy":"blur.tipsy";if(b.live)a(this.context).on(h,this.selector,d).on(n,this.selector,e);else this.bind(h,d).bind(n,e)}return this};a.fn.tipsy.defaults={aria:!0,className:null,delayIn:0,delayOut:0,fade:!1,fallback:"",gravity:"n",
html:!1,live:!1,hoverable:!0,offset:0,opacity:.8,title:"title",trigger:"hover"};a.fn.tipsy.revalidate=function(){a(".tipsy").each(function(){var b=a.data(this,"tipsy-pointee");b&&c(b)||a(this).remove()})};a.fn.tipsy.elementOptions=function(b,c){return a.metadata?a.extend({},c,a(b).metadata()):c};a.fn.tipsy.autoNS=function(){return a(this).offset().top>a(document).scrollTop()+a(window).height()/2?"s":"n"};a.fn.tipsy.autoWE=function(){return a(this).offset().left>a(document).scrollLeft()+a(window).width()/
2?"e":"w"};a.fn.tipsy.autoBounds=function(b,c){return function(){var d=c[0],e=1<c.length?c[1]:!1,f=a(document).scrollTop()+b,g=a(document).scrollLeft()+b,h=a(this);h.offset().top<f&&(d="n");h.offset().left<g&&(e="w");a(window).width()+a(document).scrollLeft()-h.offset().left<b&&(e="e");a(window).height()+a(document).scrollTop()-h.offset().top<b&&(d="s");return d+(e?e:"")}}})(jQuery);
var diacritics=function(){for(var a=[{base:" ",chars:" "},{base:"0",chars:"߀"},{base:"A",chars:"ⒶＡÀÁÂẦẤẪẨÃĀĂẰẮẴẲȦǠÄǞẢÅǺǍȀȂẠẬẶḀĄȺⱯ"},{base:"AA",chars:"Ꜳ"},{base:"AE",chars:"ÆǼǢ"},{base:"AO",chars:"Ꜵ"},{base:"AU",chars:"Ꜷ"},{base:"AV",chars:"ꜸꜺ"},{base:"AY",chars:"Ꜽ"},{base:"B",chars:"ⒷＢḂḄḆɃƁ"},{base:"C",chars:"ｃⒸＣꜾḈĆ"},{base:"D",chars:"ⒹＤḊĎḌḐḒḎĐƊƉᴅꝹ"},{base:"Dh",chars:"Ð"},{base:"DZ",chars:"ǱǄ"},{base:"Dz",chars:"ǲǅ"},{base:"E",chars:"ɛⒺＥÈÉÊỀẾỄỂẼĒḔḖĔĖËẺĚȄȆẸỆȨḜĘḘḚƐƎᴇ"},{base:"F",chars:"ꝼⒻＦḞƑꝻ"},{base:"G",
chars:"ⒼＧǴĜḠĞĠǦĢǤƓꞠꝽꝾɢ"},{base:"H",chars:"ⒽＨĤḢḦȞḤḨḪĦⱧⱵꞍ"},{base:"I",chars:"ⒾＩÌÍÎĨĪĬİÏḮỈǏȈȊỊĮḬƗ"},{base:"J",chars:"ⒿＪĴɈȷ"},{base:"K",chars:"ⓀＫḰǨḲĶḴƘⱩꝀꝂꝄꞢ"},{base:"L",chars:"ⓁＬĿĹĽḶḸĻḼḺŁȽⱢⱠꝈꝆꞀ"},{base:"LJ",chars:"Ǉ"},{base:"Lj",chars:"ǈ"},{base:"M",chars:"ⓂＭḾṀṂⱮƜϻ"},{base:"N",chars:"ꞤȠⓃＮǸŃÑṄŇṆŅṊṈƝꞐᴎ"},{base:"NJ",chars:"Ǌ"},{base:"Nj",chars:"ǋ"},{base:"O",chars:"ⓄＯÒÓÔỒỐỖỔÕṌȬṎŌṐṒŎȮȰÖȪỎŐǑȌȎƠỜỚỠỞỢỌỘǪǬØǾƆƟꝊꝌ"},{base:"OE",chars:"Œ"},{base:"OI",chars:"Ƣ"},{base:"OO",chars:"Ꝏ"},{base:"OU",chars:"Ȣ"},{base:"P",
chars:"ⓅＰṔṖƤⱣꝐꝒꝔ"},{base:"Q",chars:"ⓆＱꝖꝘɊ"},{base:"R",chars:"ⓇＲŔṘŘȐȒṚṜŖṞɌⱤꝚꞦꞂ"},{base:"S",chars:"ⓈＳẞŚṤŜṠŠṦṢṨȘŞⱾꞨꞄ"},{base:"T",chars:"ⓉＴṪŤṬȚŢṰṮŦƬƮȾꞆ"},{base:"Th",chars:"Þ"},{base:"TZ",chars:"Ꜩ"},{base:"U",chars:"ⓊＵÙÚÛŨṸŪṺŬÜǛǗǕǙỦŮŰǓȔȖƯỪỨỮỬỰỤṲŲṶṴɄ"},{base:"V",chars:"ⓋＶṼṾƲꝞɅ"},{base:"VY",chars:"Ꝡ"},{base:"W",chars:"ⓌＷẀẂŴẆẄẈⱲ"},{base:"X",chars:"ⓍＸẊẌ"},{base:"Y",chars:"ⓎＹỲÝŶỸȲẎŸỶỴƳɎỾ"},{base:"Z",chars:"ⓏＺŹẐŻŽẒẔƵȤⱿⱫꝢ"},{base:"a",chars:"ⓐａẚàáâầấẫẩãāăằắẵẳȧǡäǟảåǻǎȁȃạậặḁąⱥɐɑ"},{base:"aa",chars:"ꜳ"},{base:"ae",
chars:"æǽǣ"},{base:"ao",chars:"ꜵ"},{base:"au",chars:"ꜷ"},{base:"av",chars:"ꜹꜻ"},{base:"ay",chars:"ꜽ"},{base:"b",chars:"ⓑｂḃḅḇƀƃɓƂ"},{base:"c",chars:"ⓒćĉċčçḉƈȼꜿↄCĈĊČÇƇȻ"},{base:"d",chars:"ⓓｄḋďḍḑḓḏđƌɖɗƋᏧԁꞪ"},{base:"dh",chars:"ð"},{base:"dz",chars:"ǳǆ"},{base:"e",chars:"ⓔｅèéêềếễểẽēḕḗĕėëẻěȅȇẹệȩḝęḙḛɇǝ"},{base:"f",chars:"ⓕｆḟƒ"},{base:"ff",chars:"ﬀ"},{base:"fi",chars:"ﬁ"},{base:"fl",chars:"ﬂ"},{base:"ffi",chars:"ﬃ"},{base:"ffl",chars:"ﬄ"},{base:"g",chars:"ⓖｇǵĝḡğġǧģǥɠꞡꝿᵹ"},{base:"h",chars:"ⓗｈĥḣḧȟḥḩḫẖħⱨⱶɥ"},
{base:"hv",chars:"ƕ"},{base:"i",chars:"ⓘｉìíîĩīĭïḯỉǐȉȋịįḭɨı"},{base:"j",chars:"ⓙｊĵǰɉ"},{base:"k",chars:"ⓚｋḱǩḳķḵƙⱪꝁꝃꝅꞣ"},{base:"l",chars:"ⓛｌŀĺľḷḹļḽḻſłƚɫⱡꝉꞁꝇɭ"},{base:"lj",chars:"ǉ"},{base:"m",chars:"ⓜｍḿṁṃɱɯ"},{base:"n",chars:"ⓝｎǹńñṅňṇņṋṉƞɲŉꞑꞥлԉ"},{base:"nj",chars:"ǌ"},{base:"o",chars:"ⓞｏòóôồốỗổõṍȭṏōṑṓŏȯȱöȫỏőǒȍȏơờớỡởợọộǫǭøǿꝋꝍɵɔᴑ"},{base:"oe",chars:"œ"},{base:"oi",chars:"ƣ"},{base:"oo",chars:"ꝏ"},{base:"ou",chars:"ȣ"},{base:"p",chars:"ⓟｐṕṗƥᵽꝑꝓꝕρ"},{base:"q",chars:"ⓠｑɋꝗꝙ"},{base:"r",chars:"ⓡｒŕṙřȑȓṛṝŗṟɍɽꝛꞧꞃ"},
{base:"s",chars:"ⓢｓśṥŝṡšṧṣṩșşȿꞩꞅẛʂ"},{base:"ss",chars:"ß"},{base:"t",chars:"ⓣｔṫẗťṭțţṱṯŧƭʈⱦꞇ"},{base:"th",chars:"þ"},{base:"tz",chars:"ꜩ"},{base:"u",chars:"ⓤｕùúûũṹūṻŭüǜǘǖǚủůűǔȕȗưừứữửựụṳųṷṵʉ"},{base:"v",chars:"ⓥｖṽṿʋꝟʌ"},{base:"vy",chars:"ꝡ"},{base:"w",chars:"ⓦｗẁẃŵẇẅẘẉⱳ"},{base:"x",chars:"ⓧｘẋẍ"},{base:"y",chars:"ⓨｙỳýŷỹȳẏÿỷẙỵƴɏỿ"},{base:"z",chars:"ⓩｚźẑżžẓẕƶȥɀⱬꝣ"}],b={},c=0;c<a.length;c+=1)for(var g=a[c].chars,h=0;h<g.length;h+=1)b[g[h]]=a[c].base;return{removeDiacritics:function(a){return a.replace(/[^\u0000-\u007e]/g,
function(a){return b[a]||a})}}}();
var Limit,config,rootDocument;!function(a){a[a.All=0]="All";a[a.Two=1]="Two";a[a.One=2]="One"}(Limit||(Limit={}));
function finder(a,b){if(a.nodeType!==Node.ELEMENT_NODE)throw Error("Can't generate CSS selector for non-element node type.");if("html"===a.tagName.toLowerCase())return"html";var c={root:document.body,idName:function(a){return!0},className:function(a){return!0},tagName:function(a){return!0},attr:function(a,b){return!1},seedMinLength:1,optimizedMinLength:2,threshold:1E3,maxNumberOfTries:1E4};config=Object.assign(Object.assign({},c),b);rootDocument=findRootDocument(config.root,c);if(b=bottomUpSearch(a,
Limit.All,function(){return bottomUpSearch(a,Limit.Two,function(){return bottomUpSearch(a,Limit.One)})}))return c=sort(optimize(b,a)),0<c.length&&(b=c[0]),selector(b);throw Error("Selector was not found.");}function findRootDocument(a,b){return a.nodeType===Node.DOCUMENT_NODE?a:a===b.root?a.ownerDocument:a}
function bottomUpSearch(a,b,c){for(var g=null,h=[],e=0,f={};a&&a!==config.root.parentElement;f={$jscomp$loop$prop$l$16:f.$jscomp$loop$prop$l$16}){var d=maybe(id(a))||maybe.apply(null,$jscomp.arrayFromIterable(attr(a)))||maybe.apply(null,$jscomp.arrayFromIterable(classNames(a)))||maybe(tagName(a))||[any()];f.$jscomp$loop$prop$l$16=index(a);if(b===Limit.All)f.$jscomp$loop$prop$l$16&&(d=d.concat(d.filter(dispensableNth).map(function(a){return function(b){return nthChild(b,a.$jscomp$loop$prop$l$16)}}(f))));
else if(b===Limit.Two)d=d.slice(0,1),f.$jscomp$loop$prop$l$16&&(d=d.concat(d.filter(dispensableNth).map(function(a){return function(b){return nthChild(b,a.$jscomp$loop$prop$l$16)}}(f))));else if(b===Limit.One){var k=$jscomp.makeIterator(d=d.slice(0,1)).next().value;f.$jscomp$loop$prop$l$16&&dispensableNth(k)&&(d=[nthChild(k,f.$jscomp$loop$prop$l$16)])}k=$jscomp.makeIterator(d);for(var l=k.next();!l.done;l=k.next())l.value.level=e;if(h.push(d),h.length>=config.seedMinLength&&(g=findUniquePath(h,c)))break;
a=a.parentElement;e++}return g||(g=findUniquePath(h,c)),g}function findUniquePath(a,b){a=sort(combinations(a));if(a.length>config.threshold)return b?b():null;b=$jscomp.makeIterator(a);for(a=b.next();!a.done;a=b.next())if(a=a.value,unique(a))return a;return null}function selector(a){for(var b=a[0],c=b.name,g=1;g<a.length;g++)c=b.level===(a[g].level||0)-1?a[g].name+" > "+c:a[g].name+" "+c,b=a[g];return c}
function penalty(a){return a.map(function(a){return a.penalty}).reduce(function(a,c){return a+c},0)}function unique(a){switch(rootDocument.querySelectorAll(selector(a)).length){case 0:throw Error("Can't select any node with this selector: "+selector(a));case 1:return!0;default:return!1}}function id(a){return(a=a.getAttribute("id"))&&config.idName(a)?{name:"#"+cssesc(a,{isIdentifier:!0}),penalty:0}:null}
function attr(a){return Array.from(a.attributes).filter(function(a){return config.attr(a.name,a.value)}).map(function(a){return{name:"["+cssesc(a.name,{isIdentifier:!0})+'="'+cssesc(a.value)+'"]',penalty:.5}})}function classNames(a){return Array.from(a.classList).filter(config.className).map(function(a){return{name:"."+cssesc(a,{isIdentifier:!0}),penalty:1}})}function tagName(a){a=a.tagName.toLowerCase();return config.tagName(a)?{name:a,penalty:2}:null}function any(){return{name:"*",penalty:3}}
function index(a){var b=a.parentNode;if(!b)return null;b=b.firstChild;if(!b)return null;for(var c=0;b&&(b.nodeType===Node.ELEMENT_NODE&&c++,b!==a);)b=b.nextSibling;return c}function nthChild(a,b){return{name:a.name+(":nth-child("+b+")"),penalty:a.penalty+1}}function dispensableNth(a){return"html"!==a.name&&!a.name.startsWith("#")}function maybe(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];b=b.filter(notEmpty);return 0<b.length?b:null}function notEmpty(a){return null!=a}
function combinations(a,b){var c,g,h;return $jscomp.generator.createGenerator(combinations,function(e){switch(e.nextAddress){case 1:b=void 0===b?[]:b;if(0<a.length){e.jumpTo(2);break}return e.yield(b,0);case 2:c=$jscomp.makeIterator(a[0]),g=c.next();case 5:if(g.done){e.jumpTo(0);break}h=g.value;return e.yieldAll(combinations(a.slice(1,a.length),b.concat(h)),6);case 6:g=c.next(),e.jumpTo(5)}})}function sort(a){return Array.from(a).sort(function(a,c){return penalty(a)-penalty(c)})}
function optimize(a,b,c){var g,h,e;return $jscomp.generator.createGenerator(optimize,function(f){switch(f.nextAddress){case 1:c=void 0===c?{counter:0,visited:new Map}:c;if(!(2<a.length&&a.length>config.optimizedMinLength)){f.jumpTo(0);break}g=1;case 3:if(!(g<a.length-1)){f.jumpTo(0);break}if(c.counter>config.maxNumberOfTries)return f.return();c.counter+=1;h=[].concat($jscomp.arrayFromIterable(a));h.splice(g,1);e=selector(h);if(c.visited.has(e))return f.return();if(!unique(h)||!same(h,b)){f.jumpTo(6);
break}return f.yield(h,7);case 7:return c.visited.set(e,!0),f.yieldAll(optimize(h,b,c),8);case 8:case 6:g++,f.jumpTo(3)}})}function same(a,b){return rootDocument.querySelector(selector(a))===b}var regexAnySingleEscape=/[ -,\.\/:-@\[-\^`\{-~]/,regexSingleEscape=/[ -,\.\/:-@\[\]\^`\{-~]/,regexExcessiveSpaces=/(^|\\+)?(\\[A-F0-9]{1,6})\x20(?![a-fA-F0-9\x20])/g,defaultOptions={escapeEverything:!1,isIdentifier:!1,quotes:"single",wrap:!1};
function cssesc(a,b){b=void 0===b?{}:b;b=Object.assign(Object.assign({},defaultOptions),b);"single"!=b.quotes&&"double"!=b.quotes&&(b.quotes="single");for(var c="double"==b.quotes?'"':"'",g=b.isIdentifier,h=a.charAt(0),e="",f=0,d=a.length;f<d;){var k=a.charAt(f++),l=k.charCodeAt(0),n=void 0;32>l||126<l?(55296<=l&&56319>=l&&f<d&&(k=a.charCodeAt(f++),56320==(64512&k)?l=((1023&l)<<10)+(1023&k)+65536:f--),n="\\"+l.toString(16).toUpperCase()+" "):n=b.escapeEverything?regexAnySingleEscape.test(k)?"\\"+
k:"\\"+l.toString(16).toUpperCase()+" ":/[\t\n\f\r\x0B]/.test(k)?"\\"+l.toString(16).toUpperCase()+" ":"\\"==k||!g&&('"'==k&&c==k||"'"==k&&c==k)||g&&regexSingleEscape.test(k)?"\\"+k:k;e+=n}return g&&(/^-[-\d]/.test(e)?e="\\-"+e.slice(1):/\d/.test(h)&&(e="\\3"+h+" "+e.slice(1))),e=e.replace(regexExcessiveSpaces,function(a,b,c){return b&&b.length%2?a:(b||"")+c}),!g&&b.wrap?c+e+c:e}
;
